version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.10

  working_directory: /go/src/github.com/itzg/rcon-cli


jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - cache-{{ arch }}-{{ .Branch }}
            - cache

      - run: dep ensure -vendor-only

      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

      - run: go test

  release:
    <<: *defaults
    steps:
      - checkout

      - run: dep ensure -vendor-only

      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: goreleaser
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  incremental:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/